CREATE TABLE PROJECTINFO(
PRI_NO NUMBER PRIMARY KEY,     
PRI_TYPE VARCHAR2(10),          
PRI_LOCATION VARCHAR2(20),     
PRI_START_TIME DATE,            
PRI_ASSISTANT VARCHAR2(10),     
PRI_STATUS VARCHAR2(20),        
UPDATE_TIME DATE,               
CRETE_TIME DATE              
);
