CREATE TABLE STUDYTRACK
(
   TRACK_ID           NUMBER PRIMARY KEY NOT NULL,
   STU_ID             NUMBER,
   SUBJECT_NO         NUMBER,
   TO_COMPANY_TIME    DATE,
   ATTENDANCE_STATUS  VARCHAR2(40),
   PERFORMANCE        VARCHAR2(40),
   TASK_RESPONSE      VARCHAR2(40),
   UPDATE_TIME        DATE,
   CRETE_TIME         DATE
);