CREATE TABLE SUBJECT
(
 SUBJECT_NO  NUMBER PRIMARY KEY NOT NULL,
 SUBJECT_NAME  VARCHAR2(20),
 SUBJECT_TIMES NUMBER,
 SUBJECT_PRJ_MANAGER NUMBER,
 UPDATE_TIME         DATE,
 CRETE_TIME          DATE
)