CREATE TABLE TESTRESULT(
TEST_NO NUMBER(15) PRIMARY KEY,
SUBJECT_NO NUMBER(10),
STU_ID NUMBER(15),
TEST_SCORE NUMBER(20),
TEST_STATUS VARCHAR2(40),
TEST_TIME DATE,
UPDATE_TIME DATE,
CRETE_TIME DATE
);